name: Post every 24 hours

on:
  schedule:
    - cron: "0 0 * * *" # every 24 hours
  
  workflow_dispatch:

jobs:
  create-post-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: image_gen_PY

    - name: Download Image Log file
      uses: dawidd6/action-download-artifact@v3
      with:
        name: image_log
        path: ./image_gen_PY/
        if_no_artifact_found: warn
        search_artifacts: true
    
    - name: Run Python script
      run: python image_gen.py
      env:
        UNSPLASH_CLIENT_ID: ${{ secrets.UNSPLASH_CLIENT_ID }}
      working-directory: image_gen_PY

    - name: Upload Image Log file
      uses: actions/upload-artifact@v4
      with:
        name: image_log
        path: ./image_gen_PY/image_log.txt
    
    - name: Upload post image to artifact
      uses: actions/upload-artifact@v4
      with:
        name: post_image
        path: currentImage.png

  deploy-website:
    runs-on: ubuntu-latest
    needs: create-post-image

    permissions:
      pages: write
      id-token: write

    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Check repository
      uses: actions/checkout@v4

    - name: Download post image
      uses: actions/download-artifact@v4
      with:
        name: post_image

    - name: Put post image into website
      run: cp currentImage.png ./html/

    - name: Upload website to artifact
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: html/

    - name: Deploy website
      uses: actions/deploy-pages@v3
      with:
        artifact_name: website

    

  post-to-bsky:

    runs-on: ubuntu-latest
    needs:  create-post-image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install
      working-directory: bluesky_post_TS
        
    - name: Download post image
      uses: actions/download-artifact@v4
      with:
        name: post_image

    - name: Create post
      run: npm run start
      env:
        HANDLE: ${{ vars.HANDLE }}
        PASSWORD: ${{ secrets.PASSWORD }}
      working-directory: bluesky_post_TS
